library(affy)
library(org.Rn.eg.db)
library(org.Hs.eg.db)
library(xlsxjars)
library(rJava)
library(xlsx)
library(DOSE)
library(clusterProfiler)
library(psych)
library("readr")  
library(caret)
library(randomForest)
library(e1071)
library(gbm)
library(mlbench)
library(caretEnsemble)
library(topGO)
library(drc)
library(parallel)
source('./function.R')


drug_matrix<-read.table("./Affymetrix_Microarray_Data_Labels_spreadsheet_02_23_2012.csv",sep = '\t')
drug_matrix=drug_matrix[2:length(drug_matrix[,1]),]
liver=liverData(drug_matrix)
liver_drug=drug_spl(liver)
liver_1d=timeFilt(liver_drug)
liver_1d_max=getData(liver_1d)
control=read.table("./liver-normalization-mas5.txt",sep='\n')
match=read.table("./Affymetrix_treated to control liver.txt",sep = '\t')
drug_treat1=drug_data(liver_1d_max,'./drug_matrix/drugs/')
control_exp=control_sel(liver_1d_max,match,control,drug_treat1)
control_1=2^control_exp
control2=drug_treat1/control_1
dm=log2(control2)
write.csv(dm,'./drug_matrix/dm.csv')
p_id=colnames(control2)
gene=read.csv('./acarbose_H.csv',header = TRUE)
entr=convertID(p_id,gene)
finalDM=getCol2(dm,entr)
mergeDM<-geneMean2(finalDM)
difGene_DM=findDiffGene(mergeDM)


dmCount=egoSel(mergeDM,difGene_DM,colnames(mergeDM))
batchFS(mergeDM,dmCount,1,20,'./dm_rat_invivo/mean/','mean')
batchFS(mergeDM,dmCount,1,20,"./dm_rat_invivo/sum/",'sum')
batchFS(mergeDM,dmCount,1,20,"./dm_rat_invivo/sd/",'sd')
batchFS(mergeDM,dmCount,1,20,"./dm_rat_invivo/max/",'max')
selData=countSel(mergeDM,dmCount,19)
selData=cbind(selData[,1],selData)
pic_score<-picGener_score(selData,'ego')
pic<-PicGener(selData,pic_score)

min_matrix<-getMost(pic,'min')
max_matrix<-getMost(pic,'max')
max_matrix=max_matrix+0.00001
pic_normal<-lapply(pic,MatrixNormal,max_matrix,min_matrix)
listWrite(pic_normal,'./dm_rat_invivo/pic/')